version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: django-awards-db
    restart: always
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env.dev
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postfgresql/data
      # Create tables if not exists
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-awards-web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db