version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: django-awards-db
    restart: always
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env.dev
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postfgresql/data
      # Create tables or databases if not exists
      # - ./db:/docker-entrypoint-initdb.d/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-awards-web
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: django-awards-nginx
    ports:
      - 1337:80
    depends_on:
      - web