# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: daniel
      MONGO_INITDB_ROOT_PASSWORD: caamal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: daniel
      ME_CONFIG_MONGODB_ADMINPASSWORD: caamal
      ME_CONFIG_MONGODB_URL: mongodb://daniel:caamal@mongo:27017/